import type { Room, RoomSeatRosterEntry } from "./types";

export const logoUrl = "https://www.figma.com/api/mcp/asset/3904d8cc-02af-4b95-8868-0b1ab0418b66";

const prototypeRoomDefaults = {
  hostPlayerId: "prototype-host",
  hasStarted: false,
  hostName: "riverrat",
  buyInRange: { min: 40, max: 200 },
  players: [],
  pendingBuyIns: [],
  openSeatNumbers: [],
  waitlistRoster: [],
};

function seatRoster(entries: Array<{ name: string | null; isHost?: boolean; stack: string | null }>): RoomSeatRosterEntry[] {
  return entries.map((entry, index) => ({
    seatNumber: index + 1,
    playerId: entry.name ? `${entry.name}-id` : null,
    displayName: entry.name,
    isHost: entry.isHost ?? false,
    stack: entry.stack,
  }));
}

export const defaultRooms: Room[] = [
  {
    ...prototypeRoomDefaults,
    id: "gilt-room",
    name: "Gilt Room",
    variant: "No Limit Hold'em",
    blinds: "$2/$5",
    buyIn: "$100-$500",
    buyInRange: { min: 100, max: 500 },
    seats: "4/6",
    occupiedSeats: 4,
    seatCount: 6,
    seatRoster: seatRoster([
      { name: "riverrat", isHost: true, stack: "$200.00" },
      { name: "magpie", stack: "$200.00" },
      { name: "kings_up", stack: "$200.00" },
      { name: "longshot", stack: "$200.00" },
      { name: null, stack: null },
      { name: null, stack: null },
    ]),
    timer: "30s",
    status: "Seats open",
    featured: true,
  },
  {
    ...prototypeRoomDefaults,
    id: "marble-hall",
    name: "Marble Hall",
    variant: "No Limit Hold'em",
    blinds: "$0.50/$1",
    buyIn: "$20-$100",
    buyInRange: { min: 20, max: 100 },
    seats: "5/6",
    occupiedSeats: 5,
    seatCount: 6,
    seatRoster: seatRoster([
      { name: "marble_host", isHost: true, stack: "$80.00" },
      { name: "riverline", stack: "$80.00" },
      { name: "turn_card", stack: "$80.00" },
      { name: "smallblind", stack: "$80.00" },
      { name: "buttoncut", stack: "$80.00" },
      { name: null, stack: null },
    ]),
    timer: "30s",
    status: "Seats open",
  },
  {
    ...prototypeRoomDefaults,
    id: "chandelier",
    name: "Chandelier",
    variant: "No Limit Hold'em",
    blinds: "$5/$10",
    buyIn: "$400-$1000",
    buyInRange: { min: 400, max: 1000 },
    seats: "3/6",
    occupiedSeats: 3,
    seatCount: 6,
    seatRoster: seatRoster([
      { name: "chandelier_host", isHost: true, stack: "$800.00" },
      { name: "deepstack", stack: "$800.00" },
      { name: "top_pair", stack: "$800.00" },
      { name: null, stack: null },
      { name: null, stack: null },
      { name: null, stack: null },
    ]),
    timer: "30s",
    status: "Seats open",
  },
  {
    ...prototypeRoomDefaults,
    id: "sapphire-lounge",
    name: "Sapphire Lounge",
    variant: "No Limit Hold'em",
    blinds: "$1/$3",
    buyIn: "$60-$300",
    buyInRange: { min: 60, max: 300 },
    seats: "2/6",
    occupiedSeats: 2,
    seatCount: 6,
    seatRoster: seatRoster([
      { name: "sapphire_host", isHost: true, stack: "$180.00" },
      { name: "bluechip", stack: "$180.00" },
      { name: null, stack: null },
      { name: null, stack: null },
      { name: null, stack: null },
      { name: null, stack: null },
    ]),
    timer: "30s",
    status: "Seats open",
  },
  {
    ...prototypeRoomDefaults,
    id: "brass-cage",
    name: "Brass Cage - HU",
    variant: "No Limit Hold'em",
    blinds: "$10/$25",
    buyIn: "$1000-$2500",
    buyInRange: { min: 1000, max: 2500 },
    seats: "1/2",
    occupiedSeats: 1,
    seatCount: 2,
    seatRoster: seatRoster([
      { name: "brass_host", isHost: true, stack: "$1500.00" },
      { name: null, stack: null },
    ]),
    timer: "30s",
    status: "Seats open",
  },
  {
    ...prototypeRoomDefaults,
    id: "penny-parlor",
    name: "Penny Parlor",
    variant: "No Limit Hold'em",
    blinds: "$0.10/$0.25",
    buyIn: "$5-$25",
    buyInRange: { min: 5, max: 25 },
    seats: "6/6",
    occupiedSeats: 6,
    seatCount: 6,
    seatRoster: seatRoster([
      { name: "penny_host", isHost: true, stack: "$20.00" },
      { name: "nickel", stack: "$20.00" },
      { name: "dime", stack: "$20.00" },
      { name: "quarter", stack: "$20.00" },
      { name: "button", stack: "$20.00" },
      { name: "cutoff", stack: "$20.00" },
    ]),
    timer: "30s",
    status: "Full",
    full: true,
  },
];
