import type { Room } from "./types";

export const logoUrl = "https://www.figma.com/api/mcp/asset/3904d8cc-02af-4b95-8868-0b1ab0418b66";

const prototypeRoomDefaults = {
  hostPlayerId: "prototype-host",
  hostName: "riverrat",
  buyInMinValue: 40,
  players: [],
  pendingBuyIns: [],
  openSeatNumbers: [],
};

export const defaultRooms: Room[] = [
  {
    ...prototypeRoomDefaults,
    id: "gilt-room",
    name: "Gilt Room",
    variant: "No Limit Hold'em",
    blinds: "$2/$5",
    buyIn: "$100-$500",
    seats: "4/6",
    occupiedSeats: 4,
    seatCount: 6,
    seatLabels: [
      { label: "riverrat · host", stack: "$200.00" },
      { label: "magpie", stack: "$200.00" },
      { label: "kings_up", stack: "$200.00" },
      { label: "longshot", stack: "$200.00" },
      { label: "Seat 5 - waiting...", stack: null },
      { label: "Seat 6 - waiting...", stack: null },
    ],
    timer: "30s",
    status: "Seats open",
    featured: true,
  },
  {
    ...prototypeRoomDefaults,
    id: "marble-hall",
    name: "Marble Hall",
    variant: "No Limit Hold'em",
    blinds: "$0.50/$1",
    buyIn: "$20-$100",
    seats: "5/6",
    occupiedSeats: 5,
    seatCount: 6,
    seatLabels: [
      { label: "marble_host · host", stack: "$80.00" },
      { label: "riverline", stack: "$80.00" },
      { label: "turn_card", stack: "$80.00" },
      { label: "smallblind", stack: "$80.00" },
      { label: "buttoncut", stack: "$80.00" },
      { label: "Seat 6 - waiting...", stack: null },
    ],
    timer: "30s",
    status: "Seats open",
  },
  {
    ...prototypeRoomDefaults,
    id: "chandelier",
    name: "Chandelier",
    variant: "No Limit Hold'em",
    blinds: "$5/$10",
    buyIn: "$400-$1000",
    seats: "3/6",
    occupiedSeats: 3,
    seatCount: 6,
    seatLabels: [
      { label: "chandelier_host · host", stack: "$800.00" },
      { label: "deepstack", stack: "$800.00" },
      { label: "top_pair", stack: "$800.00" },
      { label: "Seat 4 - waiting...", stack: null },
      { label: "Seat 5 - waiting...", stack: null },
      { label: "Seat 6 - waiting...", stack: null },
    ],
    timer: "30s",
    status: "Seats open",
  },
  {
    ...prototypeRoomDefaults,
    id: "sapphire-lounge",
    name: "Sapphire Lounge",
    variant: "No Limit Hold'em",
    blinds: "$1/$3",
    buyIn: "$60-$300",
    seats: "2/6",
    occupiedSeats: 2,
    seatCount: 6,
    seatLabels: [
      { label: "sapphire_host · host", stack: "$180.00" },
      { label: "bluechip", stack: "$180.00" },
      { label: "Seat 3 - waiting...", stack: null },
      { label: "Seat 4 - waiting...", stack: null },
      { label: "Seat 5 - waiting...", stack: null },
      { label: "Seat 6 - waiting...", stack: null },
    ],
    timer: "30s",
    status: "Seats open",
  },
  {
    ...prototypeRoomDefaults,
    id: "brass-cage",
    name: "Brass Cage - HU",
    variant: "No Limit Hold'em",
    blinds: "$10/$25",
    buyIn: "$1000-$2500",
    seats: "1/2",
    occupiedSeats: 1,
    seatCount: 2,
    seatLabels: [
      { label: "brass_host · host", stack: "$1500.00" },
      { label: "Seat 2 - waiting...", stack: null },
    ],
    timer: "30s",
    status: "Seats open",
  },
  {
    ...prototypeRoomDefaults,
    id: "penny-parlor",
    name: "Penny Parlor",
    variant: "No Limit Hold'em",
    blinds: "$0.10/$0.25",
    buyIn: "$5-$25",
    seats: "6/6",
    occupiedSeats: 6,
    seatCount: 6,
    seatLabels: [
      { label: "penny_host · host", stack: "$20.00" },
      { label: "nickel", stack: "$20.00" },
      { label: "dime", stack: "$20.00" },
      { label: "quarter", stack: "$20.00" },
      { label: "button", stack: "$20.00" },
      { label: "cutoff", stack: "$20.00" },
    ],
    timer: "30s",
    status: "Full",
    full: true,
  },
];
